{
 "title": "Clipper",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "About",
   "type": "text",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "content": "# Clipper RISE Camp Tutorial Dashboard\n\nThis dashboard demonstrates Clipper serving models used in the tutorials\n\nWe show a mix of user defined metric, clipper public metrics, as well as internal metrics. "
  },
  {
   "title": "Total Predictions Made",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "internal_aggregate_num_predictions_count"
    }
   ]
  },
  {
   "title": "Cache Hit Ratio",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "internal_prediction_cache_hit_ratio_ratio"
    }
   ]
  },
  {
   "title": "Prediction Count by Model Container",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "clipper_mc_pred_total", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "End to End Latency (ms)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "clipper_mc_end_to_end_latency_ms_sum/clipper_mc_end_to_end_latency_ms_count"
    }
   ]
  },
  {
   "title": "Custom Metric: Processing Batch Size for SqueezeNet Model",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "batch_size" }
   ]
  }
 ]
}