include ../Makefile.inc

# We use host network to comminicate with our containers
# We use /tmp directory to store artifact for container building
DOCKER_RUN_FLAGS += --network host -v /tmp:/tmp

# This is Simon Mo <xmo@berkeley.edu>'s dockerhub
DOCKER_TAG = simonmok/risecamp2018-clipper
