#!/bin/bash
set -o errexit

if [[ "$1" = "" ]] || ! [[ "$2" = "" ]]; then
  echo "Usage: ./runtutorial (modin|autopandas|mc2)" >&2
  exit 1
fi

PROJ=$1
TAG="ucbrise/risecamp2019-${PROJ}:latest"

# enable access with password "risecamp2019"
NOTEBOOK_FLAGS+=" --NotebookApp.password='sha1:d3b13647d5d3:7920cbf16c6426590736d941cba5d1d2e3252060'"
NOTEBOOK_FLAGS+=" --NotebookApp.allow_origin='*'"
#NOTEBOOK_FLAGS+=" --NotebookApp.allow_remote_access=True"

# make sure we have the latest image
docker pull "$TAG"

# boot container
echo "************************************************************"
echo "***"
echo "*** RISE Camp 2019"
echo "***"
echo "*** Tutorial: $PROJ"
echo "*** Login URL: http://127.0.0.1:8080/camp/$PROJ"
echo "*** Password: risecamp2019"
echo "***"
echo "************************************************************"
echo

if [[ "$PROJ" = "mc2" ]]; then
  DOCKER_RUN_FLAGS+=" --network 'campnet-mc2'"
fi

docker run \
  --rm \
  --name "risecamp_${PROJ}" \
  --user root \
  -p 127.0.0.1:8080:8080 \
  --memory 16g \
  --shm-size 16g \
  -e "NOTEBOOK_FLAGS=${NOTEBOOK_FLAGS}" \
  -e "CONTAINER_BASE_URL=camp/${PROJ}" \
  ${DOCKER_RUN_FLAGS} \
  "$TAG"
